openapi: 3.0.3
info:
  title: Laravel
  description: ''
  version: 1.0.0
servers:
  -
    url: 'http://localhost'
paths:
  /api/auth/login:
    post:
      summary: 'Handle user login'
      operationId: handleUserLogin
      description: ''
      parameters: []
      responses: {  }
      tags:
        - Endpoints
      requestBody:
        required: true
        content:
          application/json:
            schema:
              type: object
              properties:
                email:
                  type: string
                  description: ''
                  example: rath.gaston@example.org
                  nullable: false
                password:
                  type: string
                  description: ''
                  example: U7s@.dwZ>a^
                  nullable: false
              required:
                - email
                - password
      security: []
  /api/auth/register:
    post:
      summary: 'Handle user registration with medical facility support'
      operationId: handleUserRegistrationWithMedicalFacilitySupport
      description: ''
      parameters: []
      responses: {  }
      tags:
        - Endpoints
      requestBody:
        required: true
        content:
          multipart/form-data:
            schema:
              type: object
              properties:
                name:
                  type: string
                  description: 'Must be at least 4 characters.'
                  example: dfdamijvbapjmungzenahjpegzrik
                  nullable: false
                email:
                  type: string
                  description: 'Must be a valid email address.'
                  example: wkuhn@example.net
                  nullable: false
                password:
                  type: string
                  description: 'Must be at least 6 characters.'
                  example: 'wpx_Wh?5k4K'
                  nullable: false
                user_type:
                  type: string
                  description: ''
                  example: medical_facility
                  nullable: false
                  enum:
                    - finder
                    - medical_facility
                whatsapp_number:
                  type: string
                  description: ''
                  example: est
                  nullable: false
                image:
                  type: string
                  format: binary
                  description: 'Must be an image.'
                  nullable: true
              required:
                - name
                - email
                - password
                - user_type
                - whatsapp_number
      security: []
  /api/auth/logout:
    post:
      summary: 'Handle user logout'
      operationId: handleUserLogout
      description: ''
      parameters: []
      responses: {  }
      tags:
        - Endpoints
      security: []
  /api/auth/profile:
    get:
      summary: 'Get authenticated user profile'
      operationId: getAuthenticatedUserProfile
      description: ''
      parameters: []
      responses:
        401:
          description: ''
          content:
            application/json:
              schema:
                type: object
                example:
                  message: Unauthenticated.
                properties:
                  message:
                    type: string
                    example: Unauthenticated.
      tags:
        - Endpoints
      security: []
  '/api/medical-facilities/{facility}':
    put:
      summary: ''
      operationId: putApiMedicalFacilitiesFacility
      description: ''
      parameters: []
      responses: {  }
      tags:
        - Endpoints
      requestBody:
        required: true
        content:
          multipart/form-data:
            schema:
              type: object
              properties:
                name:
                  type: string
                  description: 'Must be at least 4 characters.'
                  example: xetxiuduynzlkbjiibseprbbsqrxhvovwwezcbmswzbzziacyqtofyynvvemnuzqimbyombk
                  nullable: false
                email:
                  type: string
                  description: 'Must be a valid email address.'
                  example: sveum@example.com
                  nullable: false
                password:
                  type: string
                  description: 'Must be at least 6 characters.'
                  example: "*Yn'f/b2"
                  nullable: false
                user_type:
                  type: string
                  description: ''
                  example: finder
                  nullable: false
                  enum:
                    - finder
                    - medical_facility
                whatsapp_number:
                  type: string
                  description: 'Must not be greater than 12 characters.'
                  example: yz
                  nullable: false
                image:
                  type: string
                  format: binary
                  description: 'Must be an image.'
                  nullable: true
                address:
                  type: string
                  description: 'Must not be greater than 255 characters.'
                  example: galx
                  nullable: false
                description:
                  type: string
                  description: ''
                  example: 'Temporibus dolor nulla dolorem aut omnis et.'
                  nullable: false
                emergency_contact:
                  type: string
                  description: 'Must not be greater than 12 characters.'
                  example: mgvrygy
                  nullable: false
                google_map_url:
                  type: string
                  description: ''
                  example: 'http://www.collier.info/consequatur-natus-quo-fugiat-exercitationem-earum-est-natus.html'
                  nullable: false
                operating_hours:
                  type: array
                  description: ''
                  example:
                    - []
                  items:
                    type: object
                    properties:
                      day:
                        type: string
                        description: ''
                        example: tuesday
                        nullable: false
                        enum:
                          - monday
                          - tuesday
                          - wednesday
                          - thursday
                          - friday
                          - saturday
                          - sunday
                      open:
                        type: string
                        description: 'Must be a valid date in the format <code>H:i</code>.'
                        example: '10:20'
                        nullable: false
                      close:
                        type: string
                        description: 'Must be a valid date in the format <code>H:i</code>.'
                        example: '10:20'
                        nullable: false
                    required:
                      - day
                      - open
                      - close
                status:
                  type: string
                  description: ''
                  example: inactive
                  nullable: false
                  enum:
                    - active
                    - inactive
                    - pending
                category:
                  type: string
                  description: ''
                  example: 'Health Care'
                  nullable: false
                  enum:
                    - 'Health Care'
                    - Pharmacy
                    - Clinic
                units:
                  type: array
                  description: 'The <code>id</code> of an existing record in the units table.'
                  example: null
                  items:
                    type: string
              required:
                - name
                - email
                - password
                - user_type
                - whatsapp_number
                - address
                - description
                - operating_hours
                - status
                - category
      security: []
    parameters:
      -
        in: path
        name: facility
        description: ''
        example: qui
        required: true
        schema:
          type: string
  '/api/medical-facilities/{facility_id}':
    delete:
      summary: 'Delete a medical facility and its relationships'
      operationId: deleteAMedicalFacilityAndItsRelationships
      description: ''
      parameters: []
      responses: {  }
      tags:
        - Endpoints
      security: []
    get:
      summary: 'Show single medical facility details'
      operationId: showSingleMedicalFacilityDetails
      description: ''
      parameters: []
      responses:
        404:
          description: ''
          content:
            application/json:
              schema:
                type: object
                example:
                  message: 'No query results for model [App\Models\MedicalFacility] 11'
                properties:
                  message:
                    type: string
                    example: 'No query results for model [App\Models\MedicalFacility] 11'
      tags:
        - Endpoints
      security: []
    parameters:
      -
        in: path
        name: facility_id
        description: 'The ID of the facility.'
        example: 12
        required: true
        schema:
          type: integer
  /api/units:
    get:
      summary: 'List all medical units with pagination'
      operationId: listAllMedicalUnitsWithPagination
      description: ''
      parameters: []
      responses:
        401:
          description: ''
          content:
            application/json:
              schema:
                type: object
                example:
                  message: Unauthenticated.
                properties:
                  message:
                    type: string
                    example: Unauthenticated.
      tags:
        - Endpoints
      security: []
    post:
      summary: ''
      operationId: postApiUnits
      description: ''
      parameters: []
      responses: {  }
      tags:
        - Endpoints
      requestBody:
        required: true
        content:
          application/json:
            schema:
              type: object
              properties:
                name:
                  type: string
                  description: 'Must not be greater than 255 characters.'
                  example: ebkxbnvooqi
                  nullable: false
                description:
                  type: string
                  description: ''
                  example: 'Adipisci possimus corrupti provident ut et eos deserunt.'
                  nullable: false
                status:
                  type: string
                  description: ''
                  example: inactive
                  nullable: false
                  enum:
                    - active
                    - inactive
              required:
                - name
                - description
                - status
      security: []
  '/api/units/{id}':
    get:
      summary: 'Show single unit details'
      operationId: showSingleUnitDetails
      description: ''
      parameters: []
      responses:
        401:
          description: ''
          content:
            application/json:
              schema:
                type: object
                example:
                  message: Unauthenticated.
                properties:
                  message:
                    type: string
                    example: Unauthenticated.
      tags:
        - Endpoints
      security: []
    put:
      summary: 'Update existing unit'
      operationId: updateExistingUnit
      description: ''
      parameters: []
      responses: {  }
      tags:
        - Endpoints
      requestBody:
        required: true
        content:
          application/json:
            schema:
              type: object
              properties:
                name:
                  type: string
                  description: 'Must not be greater than 255 characters.'
                  example: wc
                  nullable: false
                description:
                  type: string
                  description: ''
                  example: 'Vel aperiam optio hic nihil accusantium repudiandae eveniet.'
                  nullable: false
                status:
                  type: string
                  description: ''
                  example: active
                  nullable: false
                  enum:
                    - active
                    - inactive
              required:
                - name
                - description
                - status
      security: []
    delete:
      summary: 'Delete a unit'
      operationId: deleteAUnit
      description: ''
      parameters: []
      responses: {  }
      tags:
        - Endpoints
      security: []
    parameters:
      -
        in: path
        name: id
        description: 'The ID of the unit.'
        example: 14
        required: true
        schema:
          type: integer
  /api/medical-facilities/search:
    get:
      summary: 'Perform a general search across medical facilities'
      operationId: performAGeneralSearchAcrossMedicalFacilities
      description: ''
      parameters: []
      responses:
        200:
          description: ''
          content:
            application/json:
              schema:
                type: object
                example:
                  data: []
                  meta:
                    total: 0
                    per_page: 15
                    current_page: 1
                    last_page: 1
                properties:
                  data:
                    type: array
                    example: []
                  meta:
                    type: object
                    properties:
                      total:
                        type: integer
                        example: 0
                      per_page:
                        type: integer
                        example: 15
                      current_page:
                        type: integer
                        example: 1
                      last_page:
                        type: integer
                        example: 1
      tags:
        - Endpoints
      requestBody:
        required: true
        content:
          application/json:
            schema:
              type: object
              properties:
                query:
                  type: string
                  description: 'Must be at least 2 characters.'
                  example: cejybdbrycajlzcexmyghbkuofopzjjcqipuehlgpcpobyrmgbprtenqotzyetvd
                  nullable: false
              required:
                - query
      security: []
  /api/medical-facilities:
    get:
      summary: 'List all medical facilities with pagination'
      operationId: listAllMedicalFacilitiesWithPagination
      description: ''
      parameters: []
      responses:
        200:
          description: ''
          content:
            application/json:
              schema:
                type: object
                example:
                  data: []
                  meta:
                    total: 0
                    per_page: 15
                    current_page: 1
                    last_page: 1
                properties:
                  data:
                    type: array
                    example: []
                  meta:
                    type: object
                    properties:
                      total:
                        type: integer
                        example: 0
                      per_page:
                        type: integer
                        example: 15
                      current_page:
                        type: integer
                        example: 1
                      last_page:
                        type: integer
                        example: 1
      tags:
        - Endpoints
      security: []
tags:
  -
    name: Endpoints
    description: ''
